name: Create main promotion pull request
on:
  push:
    branches:
      - new_feature
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin new_feature:new_feature
          git reset --hard new_feature
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main-promotion
          labels: |
            enhancement
            automerge
            
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'   
